plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Exclude:
    - 'bin/**'
