services:
  postgres:
    image: postgres:16.9
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - "./config/docker/postgres/create-development-databases.sh:/docker-entrypoint-initdb.d/create-development-databases.sh:ro"
