services:
  postgres:
    image: postgres:16.9
    restart: unless-stopped
    environment:
      POSTGRES_DB: production
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # Store the database data in a persistent volume.
      - "db-data:/var/lib/postgresql/data"

  app:
    image: preventive-financial-control-app
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # Connect to the database container
      DATABASE_URL: postgresql://postgres:5432
      # Database login credentials
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      # Master key for decrypting credentials file
      RAILS_MASTER_KEY:
      # Enforce the use of TLS to encrypt HTTP connections
      ENABLE_TLS: true
      # Paths to TLS certificate and private key
      TLS_CERTIFICATE_PATH: "/app/cert.pem"
      TLS_KEY_PATH: "/app/key.pem"
    ports:
      - "80:3000"
      - "443:3001"
    volumes:
      - "./cert.pem:/app/cert.pem:ro"
      - "./key.pem:/app/key.pem:ro"

volumes:
  db-data:
