name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    # Service containers to run
    services:
      # Label used to access the service container
      postgres:
        image: postgres:16.9
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: dev

    env:
      DATABASE_URL: postgresql://app:dev@localhost:5432/development?pool=5
      RAILS_ENV: test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Run `bundle install` and cache all installed gems automatically
          bundler-cache: true

      - name: Install package dependencies using Bundler
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop --parallel
        continue-on-error: true

      - name: Create database and run seed code
        run: bundle exec rails db:create db:migrate db:seed
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Create directory for storing test reports
        run: mkdir -p test/reports/ && rm -f test/reports/*.xml

      - name: Run tests and collect coverage data
        run: bundle exec rake
        env:
          COVERAGE: 1
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
